name: Master
on:
  push:
    branches:
      - master
jobs:
  lint-build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: npm ci
      - name: lint
        run: npm run lint
      - name: Install system requirements
        run: sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get install -y wine32 wine64
      - name: Package installer
        run: |
          npx electron-forge make -p win32
          rm out/make/squirrel.windows/x64/*.nupkg
          rm out/make/squirrel.windows/x64/RELEASES
      - uses: actions/upload-artifact@v2
        with:
          name: FlyByWire Installer
          path: out/make/squirrel.windows/x64
